name: Cucumber-Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Java JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Set up Maven
    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    # Run Maven tests
    - name: Run Maven Tests
      run: mvn test

    # Upload the test report as an artifact
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-playwright-report
        path: target/cucumber-html-reports/
